services:

  postgres:
    image: postgres:16.1-alpine
    container_name: cloud-storage-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # лимиты памяти и процессора
    mem_limit: 512m
    cpus: "0.5"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network


  # REDIS сам удаляет истекшие ключи (TTL), ничего настраивать не нужно
  redis:
    image: redis:8-alpine
    container_name: cloud-storage-redis
    ports:
      - "6379:6379" # стандартный порт Redis
    volumes:
      - redis_data:/data # сохраняем данные на диске
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network


  # MINIO — S3-совместимое хранилище
  minio:
    image: minio/minio:latest
    container_name: cloud-storage-minio

    # Переменные окружения для создания admin пользователя
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minioadmin}

    # Проброс портов
    ports:
      - "9000:9000"  # API порт — для программного доступа (Java SDK)
      - "9001:9001"  # Console порт — веб-интерфейс управления

    volumes:
      - minio_data:/data

    # Команда запуска: сервер + веб-консоль на порту 9001
    command: server /data --console-address ":9001"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:
    name: cloud-storage-postgres-data
  minio_data:
    name: cloud-storage-minio-data
  redis_data:
    name: cloud-storage-redis-data

networks:
  app-network:
    driver: bridge
    name: cloud-storage-network
