server:
  port: 8080

spring:
  application:
    name: cloud-storage

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cloud_storage_db}
    username: ${SPRING_DATASOURCE_USERNAME:cloud_user}
    password: ${SPRING_DATASOURCE_PASSWORD:cloud_pass}
    driver-class-name: org.postgresql.Driver

  # validate, только проверка схемы бд, без изменений
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # включаем миграции
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml

  # НАСТРОЙКА СЕССИИ (REDIS)
  session:
    # Время жизни сессии в секундах (86400 = 24 часа)
    timeout: 86400

    # доп настройки для Redis
    redis:
      # Префикс для ключей сессий в Redis
      # В Redis ключи будут выглядеть так:
      # "[cloud-storage:session]:[sessions:abc-123-def]" пространство имен : ключ
      # Нужно как пакеты, если ключ имеет одно название, есть уникальное пространство
      namespace: "cloud-storage:session"

      # Когда сохранять сессию в Redis:
      # on_save — при каждом изменении (безопасно)
      # immediate — немедленно при любом изменении атрибутов
      flush-mode: on_save

    # ПОДКЛЮЧЕНИЕ К REDIS
  data:
    redis:
      # Адрес Redis сервера
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379

      # Пароль (если настроен в Redis)
      # password:

      timeout: 2000ms

      # Настройка клиента Lettuce
      lettuce:
        pool:
          max-active: 8  # максимум одновременных соединений
          max-idle: 8    # максимум простаивающих соединений
          min-idle: 0    # минимум простаивающих соединений

  # ЗАГРУЗКА ФАЙЛОВ
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
      resolve-lazily: true
      file-size-threshold: 0


# MINIO
minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000 }   # API адрес
  access-key: ${MINIO_ACCESS_KEY:minioadmin}     # Логин
  secret-key: ${MINIO_SECRET_KEY:minioadmin}     # Пароль
  bucket-name: user-files    # Название корзины для файлов пользователей

storage:
  init:
    enabled: true  # Контролируем запуск minIo через наш собственный флаг


logging:
  level:
    org.cloudstorage: INFO
    org.springframework.session: INFO
    org.springframework.data.redis: INFO
    org.springdoc: DEBUG
    org.springframework.web: DEBUG

# SWAGGER
springdoc:
  api-docs:
    # Путь к JSON-описанию AP
    path: /api-docs

    # Путь к веб-интерфейсу Swagger UI
  swagger-ui:
    path: /swagger-ui.html

    # Опционально: группировать эндпоинты по тегам
  # tags-sorter: alpha  # сортировка тегов по алфавиту
  # operations-sorter: method  # сортировка методов внутри тега

